name: gear
on:
  push:
  schedule:
    - cron: '* */5 * * *'
    
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  cron:
    runs-on: windows-latest
    steps:
      - name: Sending password update
        run: |
          curl "https://gear-vpn-api.vercel.app/api/gear/vpnbook?type=send-update&secret=${{secrets.GEAR_SECRET}}"
