name: gear
on:
  push:
  schedule:
    - cron: '* */3 * * *'
jobs:
  cron:
    runs-on: windows-latest
    steps:
      - name: Sending password update
        run: |
          curl "https://gear-vpn-api.vercel.app/api/gear/vpnbook?type=send-update&secret=vpnbook-update-password"
